### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by vovanec** [matryer/runner#2]
Hi, what license is it? can you please add license file for this library?

**Comment by jjmaldonis** [comment]
@matryer just pinging you on this. I'd like to use your library but I can't without a license. 

Having no license is the most prohibitive license there is, but an MIT license would be great! That's what most of the open source community uses and it looks appropriate for your package.

Let me know if you'd like a PR so you can just click "merge".

**Comment by matryer** [comment]
Sure, a PR would be great. MIT?
